language: go
go:
  - 1.13.x
services:
  - docker
before_install:
  - docker run -d -p 127.0.0.1:5432:5432 postgres
script:
  - make test-backend
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make increment-version
  - make build-docker
  - make push-docker
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git add . *.html
  - git commit -m "Updated to version $(cat version)"
  - git push origin

