language: go
go:
  - 1.13.x
services:
  - docker
before_install:
  - docker run -d -p 127.0.0.1:5432:5432 postgres
script:
  - make test-backend
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make increment-version
  - make build-docker
  - make push-docker

