# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.7

      - image: postgres:11.5
        environment:
          - POSTGRES_USER: kolo
          - POSTGRES_PASSWORD: Pass00


    steps:
      - checkout
      - run:
        name: Waiting for Postgres to be ready
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 5432 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for Postgres && exit 1
      - run: go get github.com/lib/pq
      - run: go get github.com/mattes/migrate
      - run: go get github.com/jstemmer/go-junit-report
      - run: scrips/run_migrations.sh
      - run:
        name: Setup db
        command:

      - run:
        name: Install dependencies
        command: go get -v -u

      - run:
        name: Execute tests
        command: go test -v ./...
