definitions:
  model.ErrorVo:
    properties:
      message:
        type: string
    type: object
  model.LoginResultVo:
    properties:
      token:
        type: string
      type:
        type: string
    type: object
  model.LoginVo:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  model.RegisterVo:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  model.UserVo:
    properties:
      created:
        type: string
      id:
        type: string
      name:
        type: string
      updated:
        type: string
    type: object
  security.UserClaim:
    properties:
      created:
        type: string
      id:
        type: string
      name:
        type: string
      updated:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/alive:
    get:
      operationId: alive
      produces:
      - text/plain
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Checks if the service is running
  /api/login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - description: login json
        in: body
        name: loginVo
        required: true
        schema:
          $ref: '#/definitions/model.LoginVo'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResultVo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorVo'
      summary: Login a user
  /api/profile:
    get:
      operationId: profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/security.UserClaim'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ErrorVo'
      security:
      - ApiKeyAuth: []
      summary: Returns the profile of the logged in user
  /api/register:
    post:
      consumes:
      - application/json
      operationId: register
      parameters:
      - description: register json
        in: body
        name: registerVo
        required: true
        schema:
          $ref: '#/definitions/model.RegisterVo'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserVo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorVo'
      summary: Registers a new user
swagger: "2.0"
