basePath: '{{.BasePath}}'
definitions:
  model.HttpError:
    properties:
      message:
        type: string
    type: object
  model.LoginResultVo:
    properties:
      token:
        type: string
      type:
        type: string
    type: object
  model.LoginVo:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  model.RegisterVo:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  model.UserVo:
    properties:
      created:
        type: string
      id:
        type: string
      name:
        type: string
      updated:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /api/login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - description: login json
        in: body
        name: loginVo
        required: true
        schema:
          $ref: '#/definitions/model.LoginVo'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResultVo'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HttpError'
            type: object
      summary: Login a user
  /api/register:
    post:
      consumes:
      - application/json
      operationId: register
      parameters:
      - description: register json
        in: body
        name: registerVo
        required: true
        schema:
          $ref: '#/definitions/model.RegisterVo'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserVo'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.HttpError'
            type: object
      summary: Registers a new user
swagger: "2.0"
